backend:
  name: git-gateway
  branch: main
  repo: https://github.com/dragos-vlasie/alma-calatoreste

media_folder: 'src/assets/images'
public_folder: '/_astro'

collections:
  - name: 'post'
    label: 'Post'
    folder: 'src/content/post'
    create: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Excerpt', name: 'excerpt', widget: 'string' }
      - { label: 'Category', name: 'category', widget: 'string' }
      - {
          label: 'Tags',
          name: 'tags',
          widget: 'list',
          allow_add: true,
          allow_delete: true,
          collapsed: false,
          field: { label: 'Tag', name: 'tag', widget: 'string' },
        }
      - { label: 'Image', name: 'image', widget: 'string' }
      - { label: 'Publish Date', name: 'publishDate', widget: 'datetime', required: false }
      - { label: 'Author', name: 'author', widget: 'string' }
      - { label: 'Content', name: 'body', widget: 'markdown' }
  - name: 'page'
    label: 'Page'
    folder: 'src/content/page'
    create: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Cover Image Source', name: 'coverImageSrc', widget: 'image' } # Assuming you use an image widget for cover images
      - { label: 'Post Title', name: 'postTitle', widget: 'string' }
      - { label: 'Intro Text', name: 'introText', widget: 'text' } # You can use a text widget for short descriptions
      - { label: 'Destination Text', name: 'destinationText', widget: 'text' }
      - { label: 'Content', name: 'body', widget: 'markdown' }
